name: publish to nuget
on:
    push:
        branches:
            - main
jobs:
    publish:
        name: build, pack & publish
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup dotnet
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 6.0.*
            - uses: actions/setup-java@v3
              with:
                  distribution: "temurin" # See 'Supported distributions' for available options
                  java-version: "17"
            - run: dotnet new tool-manifest
            - run: dotnet tool install Cake.Tool --version 2.2.0

            - run: dotnet cake --target=Bundle
            # Publish
            - name: publish on version change
              run: dotnet nuget push */bin/Release/*.nupkg
